spring.application.name=issue-menu-mms
 
#local
#server.port=9080
 
#live
server.port=9072
server.servlet.context-path=/issue-menu-mms
#Local
#eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
#Live
eureka.client.service-url.defaultZone=http://localhost:9070/service-registory-mms/eureka/
 
spring.datasource.url=jdbc:postgresql://localhost:5432/e_mms
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.default_schema=dbo
activiti.database-schema=dbo
 
# Hibernate settings
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
 
management.tracing.sampling.probability=1.0
otel.exporter.otlp.endpoint=http://localhost:4317
 
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

