spring.application.name=config-server

#local
server.port=8081

#live
#server.port=8081

#server.servlet.context-path=/config-server


# Enable Eureka Discovery
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Enable local file-based config
spring.profiles.active=native
spring.cloud.config.server.native.search-locations=file:///C:/configs/

# Optional (logging)
spring.cloud.config.server.native.fail-on-error=true
